"""for label

Revision ID: 3dc8e956e28e
Revises: 91d94ce0ea16
Create Date: 2024-02-25 20:11:39.726922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc8e956e28e'
down_revision = '91d94ce0ea16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('label_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_table('collaborators',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('access_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.UniqueConstraint('user_id', 'note_id', name='unique_user_note')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaborators')
    op.drop_table('labels')
    # ### end Alembic commands ###
