"""is_archieve and is_trash

Revision ID: 91d94ce0ea16
Revises: c8982a0bbccd
Create Date: 2024-02-20 11:34:36.827641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d94ce0ea16'
down_revision = 'c8982a0bbccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archieve', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_trash', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('is_trash')
        batch_op.drop_column('is_archieve')

    # ### end Alembic commands ###
